Improve general docs
trento-project/ansible pull request #31
Opened 2024-04-15 11:02 UTC by rtorrero

Update and review main readme.md

2024-04-17 15:38 UTC, abravosuse approved these changes
After installing the required ansible modules, I am able to kick the execution of the ansible playbook.

2024-04-19 08:58 UTC, EMaksy requested changes
Hey man, good job overall.
It is much better to read now!

I left some comments about some tense usage, typos and suggestions.

2024-04-19 08:58 UTC, EMaksy commented on README.md
> +than one role. Use `;` to comment out any role that you might not want to cover. Here we assume that we have a valid SSH key in `~/.ssh/id_rsa` to
What does it mean we assume ? 
```Here we assume that we have a valid SSH key in ~/.ssh/id_rsa to access each of the machines.```

Assuming, sounds a bit soft enough for a technical documentation ?

Maybe putting a requirement or must? 
What do you think?

2024-04-19 08:58 UTC, EMaksy commented on examples/single-node/README.md
> +This example portraits a single-node configuration, where all nodes are deployed on the same machine. In this deployment:
This example ```portrays``` and not ```portraits``` or ?

2024-04-19 08:58 UTC, EMaksy commented on README.md
>  > **Note**: <br />
Starting with a small letter after Note:

```to have a fully functional deployment make sure to use either an external IP or an internal IP for rabbitmq_host based on the infra network configuration``` 

Maybe we could go with
Note: 
```For a fully functional deployment .....```

2024-04-22 07:01 UTC, arbulu89 approved these changes
@rtorrero 
It looks good from my side. Just a couple of small things.
I'm fine when you fix @EMaksy suggestions

2024-04-22 07:01 UTC, arbulu89 commented on README.md
> +### 3. Setup plabook variables:
Typo `plabook` -> `playbook`

2024-04-22 07:01 UTC, arbulu89 commented on README.md
> +### 1. Clone the repository:
I'm always against of putting `:` in headers hehe
But hey, so be it

2024-04-22 14:21 UTC, rtorrero commented on README.md
> +This playbook assumes that the server where you are going to install trento-server has an activated license
I've adjusted the way it's written by making it a requirement. If it's a requirement I think it's implicit that if you don't meet the requirements, the playbook won't work.

2024-04-22 14:35 UTC, EMaksy approved these changes
Hey man good job, I just left a small nitpick. 
besides this lgtm!

2024-04-22 14:35 UTC, EMaksy commented on examples/single-node/README.md
> + - vars-with-alerting.json: In this example, we set up alerting and set the SMTP configuration. With this, important alerts should arrive at the
Just a suggestion: 

~~With this, important~~, alerts should arrive at the --> Alerts should arrive at ....

It sounds good, but in the end these are empty words. Also as a reader I start to ask my self, what about the unimportant ? :D

2024-04-22 14:43 UTC, merged